version: "2"
services:
  sexy-hub:
    image: wordpress
    container_name: ${IMAGE_NAME}
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}:${MYSQL_PORT}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DB}
    ports:
      - "${PORT}:80"
    volumes:
      - "${PWD}/html:/var/www/html"

# volumes:
#   wordpress:
